### ISSUE TITLE
apache version

### ISSUE THREAD

**Issue by yangjun2011022405** [weiboad/fiery#1]
apache version ,haha

**Comment by 137-rick** [comment]
will support this on next version

**Comment by 137-rick** [comment]
<VirtualHost *:80>
    ServerAdmin webmaster@demo.com
    DocumentRoot "e:\wwwroot\demo"
    ServerName my.demo.com
    ErrorLog "logs/my.demo.com-error.log"
    CustomLog "logs/my.demo.com-access.log" common
    SetEnv RAGNAR_LOGPATH "/data1/ragnar/"  # 这里
    SetEnv RAGNAR_IDC "0"  # 这里
    SetEnv RAGNAR_IP "192.168.1.123"  # 这里

    <Directory "e:\wwwroot\demo">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

and added on https://github.com/weiboad/fiery/blob/0.5.5/ragnarsdk/README.md

**Comment by 137-rick** [comment]
finished
