### ISSUE TITLE
中文文档错别字

### ISSUE THREAD

**Issue by bbbbbbbk** [weiboad/fiery#5]
中文文档步骤二应该是下载jar包吧

**Comment by 137-rick** [comment]
已修复~ ：）

**Comment by bbbbbbbk** [comment]
还有埋点库植入说明当中requrire_once应该是require_once,复制到IDE中发现拼写错误 ：），工具很强大，感谢分享，学习中

**Comment by 137-rick** [comment]
fixed :) 文档发现问题可以直接修改提PR
